### PR TITLE
Remove fsGroup from container security contexts

### LINKED ISSUE #57: Error applying manifest - unknown field: fsGroup
When trying to apply the manifest generated by the helm chart, get the following error:
```
error: error validating "forseti-apply.yaml": error validating data: ValidationError(Deployment.spec.template.spec.initContainers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext; if you choose to ignore these errors, turn validation off with --validate=false
```
kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:26:40Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

Let me know if you need any further info.

## Tasks
- [x] Remove **fsGroup** from container security contexts in the git-sync-init container
- [x] Remove **fsGroup** from container security contexts in the git-sync container
- [x] Remove **fsGroup** from container security contexts in the gsutil-init container
- [x] Remove **fsGroup** from container security contexts in the empty-dir-lib container
- [x] Remove **fsGroup** from container security contexts in the empty-dir-policies container
- [x] Remove **fsGroup** from container security contexts in the sql container

### PR DESCRIPTION
**Pull request by kevensen**
Resolves #57

### CODE REVIEW

**Comment by kevensen** [comment]
- [x] Test deploy via Terraform with Git repo and that CV returns violations
- [ ] Test deploy via Terraform with GCS and that CV returns violations
- [x] Test deploy via Helm only with Git repo and that CV returns violations
- [ ] Test deploy via Helm only with GCS and that CV returns violations

**Review by gkowalski-google — APPROVED** [review]
LGTM

**Pull request merged**
