### PR TITLE
fix(forseti-security): fix Helm error

### PR DESCRIPTION
**Pull request by ThibaultLengagne**
Proposal to fix an error in the Helm chart.

For more info : https://github.com/helm/helm/issues/8311

### CODE REVIEW

**Comment by ThibaultLengagne** [comment]
@googlebot I signed it!

**Comment by gkowalski-google** [comment]
Thanks for this @ThibaultLengagne, can you clarify what versions of Helm this is fixing and what version you are using? Just want to make sure this is compatible with the existing Terraform module, which I believe most people are using 0.10.4.

**Comment by ThibaultLengagne** [comment]
Hi @gkowalski-google,
- It is fixing the Helm version `helm-v2.16.8`, which uses the Go version `1.14`. In this version of Go, there is a new checker that reports errors when a parenthesized argument is used as a function : [commit](https://go-review.googlesource.com/c/go/+/217978/3/doc/go1.14.html#831)
- I am using this version of Helm : `version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}`
- It should not break previous version of Helm, as the syntax is valid for any Helm version :)

**Review by gkowalski-google — APPROVED** [review]
LGTM

**Comment by tony-mw** [comment]
Can we get a release with this fix?

**Comment by thomascrowley** [comment]
Seconding @tony-mw 's comment. Any news on this getting released?

**Comment by gkowalski-google** [comment]
To confirm, you just need us to publish a new chart to Helm Hub, correct?

**Comment by thomascrowley** [comment]
Hi @gkowalski-google, apologies for the delay your response got buried in my Junk. But yes please, now this has been merged into master it would be great if this could get published.

**Pull request merged**
